CREATE TABLE IF NOT EXISTS host_metrics_samples (
    id BIGSERIAL PRIMARY KEY,
    ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cpu_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
    mem_used_gb DOUBLE PRECISION NOT NULL DEFAULT 0,
    mem_total_gb DOUBLE PRECISION NOT NULL DEFAULT 0,
    disk_used_gb DOUBLE PRECISION NOT NULL DEFAULT 0,
    disk_total_gb DOUBLE PRECISION NOT NULL DEFAULT 0,
    net_down_mbps DOUBLE PRECISION NOT NULL DEFAULT 0,
    net_up_mbps DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS host_metrics_samples_ts_idx ON host_metrics_samples (ts DESC);
